### ISSUE TITLE
hi, would you mind share how to use armhfbuild/drone:0.5 build this image properly?

### ISSUE THREAD

**Issue by yangxuan8282** [armhf-docker-library/nginx#3]
@djmaze 

I'm trying to use `Dockerfile` and `.drone.yml` in this repo, and armhfbuild/drone:0.5 to build nginx image on raspberry pi, but got issues:

```
ERROR: 409 Conflict: cannot join network of a non running container: drone_ambassador_DUxBh3MKh0o
ambassador
1
standard_init_linux.go:178: exec user process caused "exec format error"
```

here is my docker-compose.yml for drone:

```
version: '2'

services:
  drone-server:
    image: armhfbuild/drone:0.5
    ports:
      - 8000:8000
    volumes:
      - ./drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_TIMEOUT=30m
      - DRONE_ADMIN=
      - DRONE_OPEN=true
      - DRONE_SECRET=
      - DRONE_GOGS=true
      - DRONE_GOGS_URL=

  drone-agent:
    image: armhfbuild/drone:0.5
    command: agent
    restart: always
    depends_on: [ drone-server ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=ws://drone-server:8000/ws/broker
      - DRONE_SECRET=
```
